CREATE TABLE IF NOT EXISTS TUTORIAL_DOMAIN (id INT NOT NULL AUTO_INCREMENT, title VARCHAR(255), description VARCHAR(255), published BOOLEAN, PRIMARY KEY (id));
CREATE TABLE IF NOT EXISTS MERCHANT_STORE (id INT NOT NULL AUTO_INCREMENT, name VARCHAR(255), merchantType VARCHAR(255), PRIMARY KEY (id));
